[build]
  # This is the command Netlify runs to build your site.
  command = "npm run build"

  # This is the directory where your main website files are.
  publish = "portfolio"

[functions]
  # This tells Netlify where to find your serverless functions.
  directory = "netlify/functions"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
